{% set name = "openBIS2SQLite" %}
{% set pyproject = load_file_data("../pyproject.toml", from_recipe_dir=true) %}
{% set version = pyproject.get('project').get('version') %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/BAMresearch/openBIS2SQLite/archive/refs/tags/v{{ version }}.tar.gz

build:
  skip: True  # [win or osx]
  script: python3 -m pip install . --no-deps --ignore-installed -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - pgdumplib

about:
  home: https://github.com/BAMresearch/openBIS2SQLite
  license: MIT
  license_family: MIT
  summary: One of the packages of all time
